name: Deploy to GitHub Pages
on:
  workflow_dispatch:

  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@master
    
    - name: cp
      run: |
        git status
        git checkout dd
        echo hello > hi.txt
        git add hi.txt
        git commit -m '.'
        git checkout main
        git checkout dd hi.txt
        git status
