name: AutoCopy

on:
  push:
    branches: dd


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Install mustache (to update the date)
       # run:  apk add ruby && gem install mustache
      - name:  copy file gotten
          git checkout main
          git checkout dd .build_date.md
