name: Deploy to GitHub Pages
on:
  workflow_dispatch:

  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@master
    
    - name: cp
      run: |
        git status
        git remote update
        git config --global user.email "1121656712@qq.com"
        git config --global user.name "ysfhtxn"
        git checkout dd
        pwd
        ls
        cat .build_date.md
        read mm < .build_date.md
        git checkout main
        $mm > test.md
        git status
        pwd
        ls
        #git add .
        #git commit -m '.'
        #git push origin main
