name: AutoCopy

on:
  workflow_dispatch:
  push:
    branches: dd


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Install mustache (to update the date)
       # run:  apk add ruby && gem install mustache
      - name:  copy file gotten
        run: |
          #!/bin/sh
          pwd
          ls
          git checkout dd
          cat .build_date.md > date.md
          
          git add date.md 
          git commit -m 'update .'
          git push origin main
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install pip packages
        run: |
          python -m pip install --upgrade pip
