name: AutoCopy

on:
  push:
    branches: dd


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- name: Install mustache (to update the date)
       # run:  apk add ruby && gem install mustache
      - name:  copy file gotten
        run: |
          #!/bin/sh
          pwd
          ls
          git checkout main
          cat .build_date.md > date.md
          git checkout dd -- date.md
          git add date.md 
          git commit -m 'update .'
          git push origin main
