name: AutoCopy

on:
  workflow_dispatch:
  push:
    branches: dd


jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: main
        FOLDER: public
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
