name: Deploy to GitHub Pages
on:
  workflow_dispatch:

  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@master
    
    - name: cp
      run: |
        git status
        git remote update
        git config --global user.email "1121656712@qq.com"
        git config --global user.name "ysfhtxn"
        pwd
        ls
        git checkout dd
        echo hello > hi.txt
        
        git checkout main
        git checkout dd hi.txt
        git status
        pwd
        ls
        git add .
        git commit -m '.'
        git push origin main
