name: Deploy to GitHub Pages
on:
  workflow_dispatch:

  push:	
    branches:	
      - master

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@master
        
    - name: install pip packages
      run: |
          python -m pip install --upgrade pip
          
    - name: cp
      run: |
        git status
        git remote update
        git config --global user.email "1121656712@qq.com"
        git config --global user.name "ysfhtxn"
        git checkout dd
        cat .build_date.md
        ls
        python mian.py > 11.txt
        read mm < 11.txt
        git checkout main
        echo $mm > post/test.md
        git status
        git add .
        git commit -m '.'
        git push origin main
